# TP4/configs/sage_sampling.yaml
seed: 42
device: "cuda"
epochs: 100
lr: 0.001
weight_decay: 5e-4

sage:
  hidden_dim: 128
  dropout: 0.5

sampling:
  batch_size: 128
  num_neighbors_l1: 32
  num_neighbors_l2: 16 